[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs]
    fail_deploy_on_score_thresholds = true

  [plugins.inputs.thresholds]
    performance = 0.95
  
  [[plugins.inputs.audits]]
    path = "index.html"
