name: Application's performance audit

on:
  pull_request:
    branches:
      - master

jobs:
  performance-audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Install All Dependencies
        run: npm i -f

      - name: Build
        env:
          CI: true
          NODE_OPTIONS: --max-old-space-size=4096
        run: npm run build

      - id: deploy_site_preview
        name: Deploy a site preview
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=dist --json
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_ACCESS_TOKEN }}

          NETLIFY_SITE_ID: ${{ secrets.PROJECT_ID_ON_NETLIFY }}

      - name: Wait for preview to be ready
        run: "sleep 15"

      - name: Log deploy_site_preview step output
        run: 'echo "THE OUTPUT OF deploy_site_preview step is: ${{ steps.deploy_site_preview.outputs.NETLIFY_URL }}"'
