name: Application's performance audit

on:
  pull_request:
    branches:
      - master

env:
  ENV: dev

jobs:
  performance-audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Install All Dependencies
        if: env.ENV == 'prod'
        run: npm i -f

      - name: Install Only puppeteer
        if: env.ENV == 'dev'
        run: npm install puppeteer --no-save --verbose

      - name: Build
        if: env.ENV == 'prod'
        env:
          CI: true
          NODE_OPTIONS: --max-old-space-size=4096
        run: npm run build

      - id: deploy_site_preview
        name: Deploy site preview
        if: env.ENV == 'prod'
        env:
          NETLIFY_CLI_LIBRARY_VERSION: "18.1.0"
          NETLIFY_ACCESS_TOKEN: ${{ secrets.NETLIFY_ACCESS_TOKEN }}
          PROJECT_ID_ON_NETLIFY: ${{ secrets.PROJECT_ID_ON_NETLIFY }}
        run: |
          DEPLOY_OUTPUT_IN_JSON=$(
            npx netlify-cli@$NETLIFY_CLI_LIBRARY_VERSION deploy \
              --dir=dist \
              --site=$PROJECT_ID_ON_NETLIFY \
              --auth=$NETLIFY_ACCESS_TOKEN \
              --json
          )

          echo -e "DEPLOY_OUTPUT_IN_JSON: \n$DEPLOY_OUTPUT_IN_JSON\n"

          SITE_PREVIEW_URL=$(
            echo "$DEPLOY_OUTPUT_IN_JSON" | jq -r '.deploy_url'
          )

          echo "SITE_PREVIEW_URL=$SITE_PREVIEW_URL" >> $GITHUB_OUTPUT

      - name: Performance audit
        env:
          LIGHTHOUSE_CI_CLI_LIBRARY_VERSION: "0.14.0"
          URL_OF_SITE_TO_AUDIT_PERFORMANCE: ${{
            env.ENV == 'dev' &&
            'https://web.letalk.com.br/board/410' ||
            steps.deploy_site_preview.outputs.SITE_PREVIEW_URL
            }}
        run: |
          npx @lhci/cli@$LIGHTHOUSE_CI_CLI_LIBRARY_VERSION autorun \
            --collect.url=$URL_OF_SITE_TO_AUDIT_PERFORMANCE \
            --config=ci/config/lighthouse/.lighthouserc.js

          echo "foo"
