name: Application's performance audit

on:
  pull_request:
    branches:
      - master

jobs:
  performance-audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Install All Dependencies
        run: npm i -f

      - name: Build
        env:
          CI: true
          NODE_OPTIONS: --max-old-space-size=4096
        run: npm run build

      - id: deploy_site_preview
        name: Deploy site preview
        env:
          NETLIFY_ACCESS_TOKEN: ${{ secrets.NETLIFY_ACCESS_TOKEN }}
          PROJECT_ID_ON_NETLIFY: ${{ secrets.PROJECT_ID_ON_NETLIFY }}
        run: |
          DEPLOY_OUTPUT=$(npx netlify-cli@18.1.0 deploy --dir=dist --site=${PROJECT_ID_ON_NETLIFY} --auth=${NETLIFY_ACCESS_TOKEN} --json)

          echo "DEPLOY_OUTPUT=${DEPLOY_OUTPUT}" >> $GITHUB_ENV

          echo "deploy_url=$(echo ${DEPLOY_OUTPUT} | jq -r '.url')" >> $GITHUB_OUTPUT

          echo "logs_url=$(echo ${DEPLOY_OUTPUT} | jq -r '.logs')" >> $GITHUB_OUTPUT

      - name: Display deploy information
        run: |
          echo "Preview URL: ${{ steps.deploy_preview.outputs.deploy_url }}"
          echo "Logs URL: ${{ steps.deploy_preview.outputs.logs_url }}"
