name: Application's performance audit

on:
  pull_request:
    branches:
      - master

jobs:
  performance-audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Check Node.js version
        run: 'echo "Node version is: $(node -v)"'

      - name: Get opened pull request's source branch name and save on Github environment variables
        run: |
          OPENED_PULL_REQUEST_SOURCE_BRANCH="${{ github.head_ref }}"
          echo "OPENED_PULL_REQUEST_SOURCE_BRANCH=$OPENED_PULL_REQUEST_SOURCE_BRANCH" >> $GITHUB_ENV
