name: Application's performance audit

on:
  pull_request:
    branches:
      - master

jobs:
  performance-audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Install All Dependencies
        run: npm i -f

      - name: Build
        env:
          CI: true
          NODE_OPTIONS: --max-old-space-size=4096
        run: npm run build

      - id: deploy_site_preview
        name: Deploy a site preview
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=dist --json
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_ACCESS_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.PROJECT_ID_ON_NETLIFY }}

      - name: Wait for deployment preview to be ready
        run: "sleep 30"

      - name: Try to get `deploy_site_preview` step outputs
        run: |
          echo "NETLIFY_URL::: ${{ steps.deploy_site_preview.outputs.NETLIFY_URL }}"
          echo "NETLIFY_OUTPUT::: ${{ steps.deploy_site_preview.outputs.NETLIFY_OUTPUT }}"
          echo "NETLIFY_LOGS_URL::: ${{ steps.deploy_site_preview.outputs.NETLIFY_LOGS_URL }}"
          echo "NETLIFY_LIVE_URL::: ${{ steps.deploy_site_preview.outputs.NETLIFY_LIVE_URL }}"
