name: Application's performance audit

on:
  pull_request:
    branches:
      - master

jobs:
  performance-audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Install All Dependencies
        run: npm i -f

      - name: Build
        env:
          CI: true
          NODE_OPTIONS: --max-old-space-size=4096
        run: npm run build

      - name: Get opened pull request's source branch name and save on Github environment variables
        run: |
          OPENED_PULL_REQUEST_SOURCE_BRANCH="${{ github.head_ref }}"
          echo "OPENED_PULL_REQUEST_SOURCE_BRANCH=$OPENED_PULL_REQUEST_SOURCE_BRANCH" >> $GITHUB_ENV

      - name: Deploy
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=dist
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_ACCESS_TOKEN }}

          NETLIFY_SITE_ID: ${{ secrets.PROJECT_ID_ON_NETLIFY }}
