name: Performance audit (With "Lighthouse" automated tool)

on:
  pull_request:
    branches:
      - master

jobs:
  performance-audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Start application
        run: npm run preview &

      - name: Lighthouse's performance audit
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: "http://localhost:3000"
          budgetPath: ./performance-budget.json
