name: Application's performance audit

on:
  pull_request:
    branches:
      - master

jobs:
  performance-audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Install All Dependencies
        run: npm i -f

      - name: Build
        env:
          CI: true
          NODE_OPTIONS: --max-old-space-size=4096
        run: npm run build

      - id: deploy_site_preview
        name: Deploy site preview
        env:
          NETLIFY_CLI_LIBRARY_VERSION: "18.1.0"
          NETLIFY_ACCESS_TOKEN: ${{ secrets.NETLIFY_ACCESS_TOKEN }}
          PROJECT_ID_ON_NETLIFY: ${{ secrets.PROJECT_ID_ON_NETLIFY }}
        run: |
          DEPLOY_OUTPUT_IN_JSON=$(
            npx netlify-cli@$NETLIFY_CLI_LIBRARY_VERSION deploy \
              --dir=dist \
              --site=$PROJECT_ID_ON_NETLIFY \
              --auth=$NETLIFY_ACCESS_TOKEN \
              --json
          )

          echo -e "\nDEPLOY_OUTPUT_IN_JSON: \n\n$DEPLOY_OUTPUT_IN_JSON\n"

          PREVIEW_URL=$(echo "$DEPLOY_OUTPUT_IN_JSON" | jq -r '.deploy_url')

          echo "PREVIEW_URL=$PREVIEW_URL" >> $GITHUB_ENV

      - name: Display deploy information
        run: |
          echo "Preview URL: $PREVIEW_URL"
